### ISSUE TITLE
Found with fuzzer: muse recharging wand issue

### ISSUE THREAD

**Issue by elunna** [k21971/EvilHack#109]
Found while fuzzing in wizmode with wizmakemap bound to v. Not sure what to make of it.

```
Program received signal SIGSEGV, Segmentation fault.
0x000055555586fee6 in recharge (obj=0x555555aea390, curse_bless=0, mtmp=0x555555ae7500)
    at read.c:676
676	                      : (objects[obj->otyp].oc_dir != NODIR) ? 8 : 15;
#0  0x000055555586fee6 in recharge (obj=0x555555aea390, curse_bless=0, mtmp=0x555555ae7500)
    at read.c:676
#1  0x00005555557eadd8 in use_misc (mtmp=0x555555ae7500) at muse.c:2954
#2  0x00005555557c3e29 in dochug (mtmp=0x555555ae7500) at monmove.c:634
#3  0x00005555557c118d in dochugw (mtmp=0x555555ae7500) at monmove.c:122
#4  0x0000555555796394 in movemon () at mon.c:1412
#5  0x00005555555a2eb9 in moveloop (resuming=0 '\000') at allmain.c:203
#6  0x000055555597e442 in main (argc=4, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353

Full backtrace:

#0  0x000055555586fee6 in recharge (obj=0x555555aea390, curse_bless=0, mtmp=0x555555ae7500)
    at read.c:676
        lim = 21845
        n = 1437496576
        is_cursed = 0 '\000'
        is_blessed = 0 '\000'
        yours = 0 '\000'
#1  0x00005555557eadd8 in use_misc (mtmp=0x555555ae7500) at muse.c:2954
        i = 0
        otmp = 0x555555aebb20
        vis = 0 '\000'
        vismon = 0 '\000'
        oseen = 0 '\000'
        nambuf = "\001\000\000\000G\000\000\000\021\000\000\000?\000\000\000\t\000\000\000\021\000\000\000\020\222\257UUU\000\000@\342\377\377\005\000\000\000\004\000\000\000UU\000\000\f\000\000\000\026\000\000\000\b\000\000\000\023\000\000\000\000u\256UUU\000\000 \006\244UUU", '\000' <repeats 11 times>, "u\256UUU\000\000\000\000\000\000\000\000\000\000 \006\244UUU\000\000PծUUU\000\000 \006\244UUU\000\000\020\342\377\377\377\177\000\000{\235~UUU\000\000@4\257UUU\000\000\000u\256UUU\000\000\000\000\000\000\000\000\000\000 \006\244UUU\000\000\000\000\000\000\000\000\000\000 \006\244UUU\000\000p\342\377\377\377\177\000\000\027"...
        tt = 0x4300000000
#2  0x00005555557c3e29 in dochug (mtmp=0x555555ae7500) at monmove.c:634
        mdat = 0x555555a40620 <mons+46592>
        tmp = 0
        mdummy = 0x0
        inrange = 1
        nearby = 0
        scared = 0
        oldx = 0
        oldy = 0
        mwalk_sewage = 0 '\000'
#3  0x00005555557c118d in dochugw (mtmp=0x555555ae7500) at monmove.c:122
        x = 19
        y = 8
        already_saw_mon = 0 '\000'
        rd = 300
#4  0x0000555555796394 in movemon () at mon.c:1412
        mtmp = 0x555555ae7500
        nmtmp = 0x0
        somebody_can_move = 0 '\000'
#5  0x00005555555a2eb9 in moveloop (resuming=0 '\000') at allmain.c:203
        moveamt = 18
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        timeout_start = 26835
        past_clock = 460252
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
#6  0x000055555597e442 in main (argc=4, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0xffffffff <error: Cannot access memory at address 0xffffffff>
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'

```

**Comment by k21971** [comment]
Closed via commit d5f5ab5.
