### ISSUE TITLE
panic when going down stairs

### ISSUE THREAD

**Issue by enetics-secker** [k21971/EvilHack#179]
Systems are Fedora 39 and 40.  I captured 3 instances of the game freezing solid when I go down stairs.

(gdb) 
Continuing.
Program received signal SIGINT, Interrupt.
0x000000000054e2d3 in lower_bits (x=175676520848501335) at isaac64.c:36
36		return (x & ((ISAAC64_SZ-1) << 3)) >>3;
(gdb) bt
#0  0x000000000054e2d3 in lower_bits (x=175676520848501335) at isaac64.c:36
#1  0x000000000054e584 in isaac64_update (_ctx=0x8f3d30 <rnglist+16>) at isaac64.c:68
#2  0x000000000054f18b in isaac64_next_uint64 (_ctx=0x8f3d30 <rnglist+16>) at isaac64.c:157
#3  0x0000000000718d5b in RND (x=12) at rnd.c:62
#4  0x0000000000718dc6 in rn2 (x=-1382963894) at rnd.c:109
#5  0x00000000004401cb in create_oprop (obj=0x4e041bad91a54a, allow_detrimental=0 '\000') at artifact.c:379
#6  0x00000000007391d9 in shkinit (shp=0x88e790 <shtypes+880>, sroom=0x9024b0 <rooms+9936>, shp_indx=11) at shknam.c:793
#7  0x00000000007395da in stock_room (shp_indx=11, sroom=0x9024b0 <rooms+9936>) at shknam.c:869
#8  0x0000000000749b60 in fill_room (croom=0x9024b0 <rooms+9936>, prefilled=0 '\000') at sp_lev.c:2555
#9  0x000000000074494e in fill_rooms () at sp_lev.c:819
#10 0x00000000007568b3 in sp_level_coder (lvl=0x186bca0) at sp_lev.c:6191
#11 0x0000000000756b6c in load_special (name=0x7ffc1db5afb0 "minetn-8.lev") at sp_lev.c:6289
#12 0x000000000060c6e6 in makemaz (s=0x16fffba "minetn") at mkmaze.c:1013
#13 0x0000000000603580 in makelevel () at mklev.c:815
#14 0x0000000000604aa8 in mklev () at mklev.c:1218
#15 0x00000000004ac9a4 in goto_level (newlevel=0x7ffc1db5b46e, at_stairs=1 '\001', falling=0 '\000', portal=0 '\000') at do.c:1747
#16 0x00000000004f4438 in next_level (at_stairs=1 '\001') at dungeon.c:1187
#17 0x00000000004ab80a in dodown () at do.c:1292
#18 0x0000000000479fb8 in rhack (cmd=0x8ff1e0 <in_line> ">") at cmd.c:5610
#19 0x0000000000428782 in moveloop (resuming=0 '\000') at allmain.c:882
#20 0x0000000000815d36 in main (argc=1, argv=0x7ffc1db5b798) at ../sys/unix/unixmain.c:353

===================================================================================

Starting program: /home/bouquet/games/evilhackdir/evilhack 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Suddenly, the dungeon collapses.
To report this error, Contact K2 or Tangles on Libera irc channel #hardfought
and it may be possible to rebuild.
Generating more information you may report:

[0] /home/bouquet/games/evilhackdir/evilhack() [0x50b7ed]
[1] /home/bouquet/games/evilhackdir/evilhack() [0x50b79c]
[2] /home/bouquet/games/evilhackdir/evilhack(panic+0x9e) [0x50d874]
[3] /home/bouquet/games/evilhackdir/evilhack(obj_is_local+0x69) [0x7746c3]
[4] /home/bouquet/games/evilhackdir/evilhack() [0x774786]
[5] /home/bouquet/games/evilhackdir/evilhack() [0x774811]
[6] /home/bouquet/games/evilhackdir/evilhack(save_timers+0x52) [0x774899]
[7] /home/bouquet/games/evilhackdir/evilhack(savelev+0x1eb) [0x71fdec]
[8] /home/bouquet/games/evilhackdir/evilhack(dosave0+0x31f) [0x71f42d]
[9] /home/bouquet/games/evilhackdir/evilhack(panic+0x1cd) [0x50d9a3]
[10] /home/bouquet/games/evilhackdir/evilhack(dealloc_obj+0x88) [0x61571d]
[11] /home/bouquet/games/evilhackdir/evilhack(obfree+0x287) [0x724d48]
[12] /home/bouquet/games/evilhackdir/evilhack(rot_organic+0x82) [0x497b97]
[13] /home/bouquet/games/evilhackdir/evilhack(rot_corpse+0x1b6) [0x497d50]
[14] /home/bouquet/games/evilhackdir/evilhack(run_timers+0x7d) [0x773b77]
[15] /home/bouquet/games/evilhackdir/evilhack(goto_level+0x13b4) [0x4ad429]
[16] /home/bouquet/games/evilhackdir/evilhack(next_level+0x89) [0x4f4438]
[17] /home/bouquet/games/evilhackdir/evilhack(dodown+0x1090) [0x4ab80a]
[18] /home/bouquet/games/evilhackdir/evilhack(rhack+0x6ef) [0x479fb8]
[19] /home/bouquet/games/evilhackdir/evilhack(moveloop+0x2563) [0x428782]

Program received signal SIGABRT, Aborted.
0x00007ffff7def834 in __pthread_kill_implementation () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install libgcc-13.3.1-1.fc39.x86_64

===================================================================================

Starting program: /home/bouquet/games/evilhackdir/evilhack 714011
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
MAXPLAYERS are set in sysconf file.

Suddenly, the dungeon collapses.
To report this error, Contact K2 or Tangles on Libera irc channel #hardfought
and it may be possible to rebuild.
Generating more information you may report:

[0] /home/bouquet/games/evilhackdir/evilhack() [0x50b7ed]
[1] /home/bouquet/games/evilhackdir/evilhack() [0x50b79c]
[2] /home/bouquet/games/evilhackdir/evilhack(panic+0x9e) [0x50d874]
[3] /home/bouquet/games/evilhackdir/evilhack(obj_is_local+0x69) [0x7746c3]
[4] /home/bouquet/games/evilhackdir/evilhack() [0x774786]
[5] /home/bouquet/games/evilhackdir/evilhack() [0x774811]
[6] /home/bouquet/games/evilhackdir/evilhack(save_timers+0x52) [0x774899]
[7] /home/bouquet/games/evilhackdir/evilhack(savelev+0x1eb) [0x71fdec]
[8] /home/bouquet/games/evilhackdir/evilhack(dosave0+0x31f) [0x71f42d]
[9] /home/bouquet/games/evilhackdir/evilhack(panic+0x1cd) [0x50d9a3]
[10] /home/bouquet/games/evilhackdir/evilhack(dealloc_obj+0x88) [0x61571d]
[11] /home/bouquet/games/evilhackdir/evilhack(obfree+0x287) [0x724d48]
[12] /home/bouquet/games/evilhackdir/evilhack(rot_organic+0x82) [0x497b97]
[13] /home/bouquet/games/evilhackdir/evilhack(rot_corpse+0x1b6) [0x497d50]
[14] /home/bouquet/games/evilhackdir/evilhack(run_timers+0x7d) [0x773b77]
[15] /home/bouquet/games/evilhackdir/evilhack(goto_level+0x13b4) [0x4ad429]
[16] /home/bouquet/games/evilhackdir/evilhack(next_level+0x89) [0x4f4438]
[17] /home/bouquet/games/evilhackdir/evilhack(dodown+0x1090) [0x4ab80a]
[18] /home/bouquet/games/evilhackdir/evilhack(rhack+0x6ef) [0x479fb8]
[19] /home/bouquet/games/evilhackdir/evilhack(moveloop+0x2563) [0x428782]

Program received signal SIGABRT, Aborted.
0x00007ffff7def834 in __pthread_kill_implementation () from /lib64/libc.so.6

**Comment by enetics-secker** [comment]
Got the latest version and the issue hasn't reoccured.

Unix EvilHack Version 0.8.4-0 Beta - last build Wed Jul  3 09:35:39 2024
(535b8060c45db963d0368df08a6db888d7618ddd, branch: master).
